name: medias_viewer
description: A powerful and customizable Flutter media viewer for images and videos with zoom, swipe navigation, and video controls.
version: 0.4.2
homepage: https://github.com/brix-app-team/medias-viewer
repository: https://github.com/brix-app-team/medias-viewer
issue_tracker: https://github.com/brix-app-team/medias-viewer/issues

environment:
  sdk: ^3.9.2
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Image zoom and pan
  photo_view: ^0.15.0
  
  # Video playback
  video_player: ^2.9.2
  chewie: ^1.8.5
  
  youtube_player_flutter: ^9.1.3
  
  # Utilities
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
